### ISSUE TITLE
Domain 

### ISSUE THREAD

**Issue by sonicx180** [Hyderite/Hyderite#1]
Hey Hyderite! I was wondering were you got the domain from. I think you got it from freenom but how? I try to get domains from freenom but I just get a technical error. Thanks for the response!

**Comment by Hyderite** [comment]
You have to enter your real address in Freenom. :)

**Comment by sonicx180** [comment]
I did!

**Comment by Hyderite** [comment]
**Update:**
Turns out Freenom was sued by Meta, so registering a domain on Freenom is impossible until further notice. Sorry if I'm late.
